version: "2.2"
services:
  postgres4:
    image: postgres:14.0-alpine
    env_file:
      - postgres.env
    container_name: postgres4
    restart: always
    stdin_open: true
    tty: true
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    expose:
      - ${PGPORT}
    ports:
      - "${PGPORT}:${PGPORT}"
    command: -p ${PGPORT}
    volumes:
      - postgres4:/var/lib/postgresql/data
  anylog-operator-node4:
    depends_on:
      postgres4:
        condition: service_healthy
    image: anylogco/anylog-network:predevelop
    restart: always
    env_file:
      - anylog_configs.env
    container_name: anylog-operator-node4
    stdin_open: true
    tty: true
    network_mode: "host" 
    volumes:
      - anylog-operator-node4-anylog:/app/AnyLog-Network/anylog
      - anylog-operator-node4-blockchain:/app/AnyLog-Network/blockchain
      - anylog-operator-node4-data:/app/AnyLog-Network/data
      - anylog-operator-node4-local-scripts:/app/AnyLog-Network/scripts
volumes:
  postgres4:
  anylog-operator-node4-anylog:
  anylog-operator-node4-blockchain:
  anylog-operator-node4-data:
  anylog-operator-node4-local-scripts:
