version: "2.2"
services:
  anylog-operator-node:
    image: anylogco/anylog-network:develop
    restart: always
    env_file:
      - anylog_configs.env
    container_name: anylog-operator-node
    stdin_open: true
    tty: true
    network_mode: "host" 
    volumes:
      - anylog-operator-node-anylog:/app/AnyLog-Network/anylog
      - anylog-operator-node-blockchain:/app/AnyLog-Network/blockchain
      - anylog-operator-node-data:/app/AnyLog-Network/data
      - anylog-operator-node-local-scripts:/app/AnyLog-Network/scripts
volumes:
  anylog-operator-node-anylog:
  anylog-operator-node-blockchain:
  anylog-operator-node-data:
  anylog-operator-node-local-scripts:
